# Generated by Django 4.2.2 on 2023-07-02 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                ("idCategorie", models.AutoField(primary_key=True, serialize=False)),
                ("nomCategorie", models.CharField(max_length=200)),
                ("descriptionCategorie", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("login", models.CharField(max_length=200)),
                ("mdp_hash", models.CharField(max_length=128)),
                ("nom", models.CharField(max_length=200)),
                ("prenom", models.CharField(max_length=200)),
                ("dateNaissance", models.DateField()),
                ("mail", models.EmailField(max_length=254)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Revenu",
            fields=[
                ("idRevenu", models.AutoField(primary_key=True, serialize=False)),
                ("montantRevenu", models.DecimalField(decimal_places=2, max_digits=10)),
                ("jourRevenu", models.DateField()),
                ("heureRevenu", models.TimeField()),
                (
                    "idCategorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgestionapp.categorie",
                    ),
                ),
                (
                    "idEtudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgestionapp.etudiant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Achat",
            fields=[
                ("idAchat", models.AutoField(primary_key=True, serialize=False)),
                ("montantAchat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("jourAchat", models.DateField()),
                ("heureAchat", models.TimeField()),
                (
                    "idCategorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgestionapp.categorie",
                    ),
                ),
                (
                    "idEtudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgestionapp.etudiant",
                    ),
                ),
            ],
        ),
    ]
