# Generated by Django 4.2.2 on 2023-07-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "budgestionapp",
            "0003_alter_etudiant_datenaissance_alter_etudiant_mail_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="login",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
