# Generated by Django 4.2.2 on 2023-07-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgestionapp", "0004_alter_etudiant_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="achat",
            name="descriptionAchat",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="revenu",
            name="descriptionRevenu",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
