# Generated by Django 4.2.2 on 2023-07-05 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budgestionapp", "0006_alter_achat_heureachat_alter_achat_jourachat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achat",
            name="idCategorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="budgestionapp.categorie",
            ),
        ),
        migrations.AlterField(
            model_name="revenu",
            name="idCategorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="budgestionapp.categorie",
            ),
        ),
    ]
