# Generated by Django 4.2.2 on 2023-07-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgestionapp", "0007_alter_achat_idcategorie_alter_revenu_idcategorie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="achat", old_name="descriptionAchat", new_name="description",
        ),
        migrations.RenameField(model_name="achat", old_name="idAchat", new_name="id",),
        migrations.RenameField(
            model_name="achat", old_name="jourAchat", new_name="jour",
        ),
        migrations.RenameField(
            model_name="achat", old_name="montantAchat", new_name="montant",
        ),
        migrations.RenameField(
            model_name="revenu", old_name="descriptionRevenu", new_name="description",
        ),
        migrations.RenameField(
            model_name="revenu", old_name="idRevenu", new_name="id",
        ),
        migrations.RenameField(
            model_name="revenu", old_name="jourRevenu", new_name="jour",
        ),
        migrations.RenameField(
            model_name="revenu", old_name="montantRevenu", new_name="montant",
        ),
        migrations.RemoveField(model_name="achat", name="heureAchat",),
        migrations.RemoveField(model_name="achat", name="idCategorie",),
        migrations.RemoveField(model_name="revenu", name="heureRevenu",),
        migrations.RemoveField(model_name="revenu", name="idCategorie",),
        migrations.AddField(
            model_name="achat",
            name="type",
            field=models.CharField(default="Achat", max_length=200),
        ),
        migrations.AddField(
            model_name="revenu",
            name="type",
            field=models.CharField(default="Revenu", max_length=200),
        ),
    ]
