# Generated by Django 4.2.2 on 2023-07-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgestionapp", "0008_rename_descriptionachat_achat_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiant",
            name="is_admin",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
