# Generated by Django 4.2.2 on 2023-07-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgestionapp", "0009_etudiant_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiant",
            name="etablissement",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
